<?xml version="1.0" encoding="utf-8"?><Database Name="Project Management System" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-79L809E;Initial Catalog=&quot;Project Management System&quot;;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Project_Management_SystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Evaluation" Member="Evaluations">
    <Type Name="Evaluation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="stdID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TotalMarks" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="obtainMarks" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="weightage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>