#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManger
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Project Management System")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEvaluation(Evaluation instance);
    partial void UpdateEvaluation(Evaluation instance);
    partial void DeleteEvaluation(Evaluation instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Project_Management_SystemConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Evaluation> Evaluations
		{
			get
			{
				return this.GetTable<Evaluation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Evaluation")]
	public partial class Evaluation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _stdID;
		
		private string _TotalMarks;
		
		private string _obtainMarks;
		
		private string _weightage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstdIDChanging(string value);
    partial void OnstdIDChanged();
    partial void OnTotalMarksChanging(string value);
    partial void OnTotalMarksChanged();
    partial void OnobtainMarksChanging(string value);
    partial void OnobtainMarksChanged();
    partial void OnweightageChanging(string value);
    partial void OnweightageChanged();
    #endregion
		
		public Evaluation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stdID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string stdID
		{
			get
			{
				return this._stdID;
			}
			set
			{
				if ((this._stdID != value))
				{
					this.OnstdIDChanging(value);
					this.SendPropertyChanging();
					this._stdID = value;
					this.SendPropertyChanged("stdID");
					this.OnstdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMarks", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TotalMarks
		{
			get
			{
				return this._TotalMarks;
			}
			set
			{
				if ((this._TotalMarks != value))
				{
					this.OnTotalMarksChanging(value);
					this.SendPropertyChanging();
					this._TotalMarks = value;
					this.SendPropertyChanged("TotalMarks");
					this.OnTotalMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obtainMarks", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string obtainMarks
		{
			get
			{
				return this._obtainMarks;
			}
			set
			{
				if ((this._obtainMarks != value))
				{
					this.OnobtainMarksChanging(value);
					this.SendPropertyChanging();
					this._obtainMarks = value;
					this.SendPropertyChanged("obtainMarks");
					this.OnobtainMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weightage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string weightage
		{
			get
			{
				return this._weightage;
			}
			set
			{
				if ((this._weightage != value))
				{
					this.OnweightageChanging(value);
					this.SendPropertyChanging();
					this._weightage = value;
					this.SendPropertyChanged("weightage");
					this.OnweightageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
